spring.application.name=springboot
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Rk7lXQdZD/.well-known/jwks.json
spring.datasource.url=jdbc:postgresql://localhost:5434/approval_round
spring.datasource.username=postgres
spring.datasource.password=password